# Generated by Django 5.0.1 on 2026-01-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('wine_type', models.CharField(choices=[('red', 'Красное'), ('white', 'Белое'), ('rose', 'Розовое'), ('sparkling', 'Игристое')], max_length=20, verbose_name='Тип вина')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('volume', models.IntegerField(default=750, verbose_name='Объем (мл)')),
                ('alcohol', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Крепость (%)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('grape_variety', models.CharField(max_length=200, verbose_name='Сорт винограда')),
                ('in_stock', models.BooleanField(default=True, verbose_name='В наличии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Вино',
                'verbose_name_plural': 'Вина',
                'ordering': ['-created_at'],
            },
        ),
    ]
