# Generated by Django 5.0.1 on 2026-01-13 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_country_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='main.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='wine',
            name='country_old',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Страна (старое)'),
        ),
    ]
