# Generated by Django 5.0.1 on 2026-01-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_country_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='country_old',
        ),
        migrations.AlterField(
            model_name='wine',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wines', to='main.country', verbose_name='Страна'),
        ),
    ]
